### ISSUE TITLE
[Improvement] - Add Continuous Integration

### ISSUE THREAD

**Issue by bauripalash** [cloudlibz/clocal-azure#16]
#### There is no CI Automatic Build and Test.

I think it would be very useful to add a CI service such as Travis-CI or Circle-CI which will make it possible to test the code after every push and each pull request.

**Comment by nklayman** [comment]
Could this be added as a google code in task?

**Comment by rajikaimal** [comment]
This would require login permission to the CI server. So I don't think we'll be able to provide credentials to students.
