### ISSUE TITLE
README.md is giving wrong file for environmental variables

### ISSUE THREAD

**Issue by jmularski** [cloudlibz/clocal-azure#6]
In README.md we can read that we should "Go to command.env file and specify the path to create the images for azure functions and azure api app service and azure cosmosdb.", while command.env file doesn't exist, I believe the right file is compose.env

**Comment by LeWarEnds** [comment]
Where is compose.env located?

**Comment by jmularski** [comment]
As you can see in master, I believe that it's main folder

**Comment by lakindu95** [comment]
Closing the issue as the answer provided
